### ISSUE TITLE
混淆规则？？

### ISSUE THREAD

**Issue by zp-techie** [zhouzhuo810/CameraCardCropDemo#6]

**Comment by zhouzhuo810** [comment]
不添加混淆规则会报错吗？

**Comment by zp-techie** [comment]
混淆后会报错



------------------ 原始邮件 ------------------
发件人: "周卓"<notifications@github.com>; 
发送时间: 2019年7月26日(星期五) 上午9:23
收件人: "zhouzhuo810/CameraCardCropDemo"<CameraCardCropDemo@noreply.github.com>; 
抄送: "大鹏展翅"<623301600@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhouzhuo810/CameraCardCropDemo] 混淆规则？？ (#6)




不混淆会报错吗？

**Comment by zhouzhuo810** [comment]
那就不混淆我的就行了
