### ISSUE TITLE
请修复一个错误，以及增加一个横屏显示布局

### ISSUE THREAD

**Issue by New-Zero-Zero** [zhouzhuo810/CameraCardCropDemo#7]
这个提示内容判断写反了，
     rectView.setHintTextAndTextSize((hint == null || hint.length() == 0 ? hint : CameraConfig.DEFAULT_HINT_TEXT), 30);

    可用补充一个横屏显示的布局吗？ 横屏情况下拍摄框在左侧，拍摄按钮右侧显示的布局
 android:screenOrientation="landscape"

**Comment by zhouzhuo810** [comment]
有空试试

**Comment by zhouzhuo810** [comment]
已添加
